remote_theme: just-the-docs/just-the-docs

title: WLEDger
description: A fast, lightweight, and robust web application for managing and locating hobby parts inventory using WLED.

color_scheme: "dark"

aux_links:
  "WLEDger on GitHub":
    - "https://github.com/tuxedocurly/wledger"